# Generated by Django 3.2.4 on 2021-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_auto_20210625_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default='Hello'),
            preserve_default=False,
        ),
    ]
