# Generated by Django 3.2.4 on 2021-07-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_note_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
